spring:
  application:
    name: spring-cloud-example-gateway
  
            
server:
  port: 8002

# Eureka相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60  # 发呆时间，即服务续约到期时间（缺省为90s）
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
    

            
my-load-balanced-service:
  ribbon:
    listOfServers: localhost:8010,localhost:8012,localhost:8013,
                   localhost:8011,localhost:8014
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule